name       : python-more-itertools
version    : 4.3.0
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/m/more-itertools/more-itertools-4.3.0.tar.gz : c476b5d3a34e12d40130bc2f935028b5f636df8f372dc2c1c01dc19681b2039e
license    : MIT
component  : programming.python
summary    : More routines for operating on iterables, beyond itertools
description: |
    Python's `itertools` library is a gem - you can compose elegant solutions for a variety of problems with the functions it provides. In `more-itertools` we collect additional building blocks, recipes, and routines for working with Python iterables.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
