name       : python-more-itertools
version    : 5.0.0
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/m/more-itertools/more-itertools-5.0.0.tar.gz : 38a936c0a6d98a38bcc2d03fdaaedaba9f412879461dd2ceff8d37564d6522e4
license    : MIT
component  : programming.python
summary    : More routines for operating on iterables, beyond itertools
description: |
    Python's `itertools` library is a gem - you can compose elegant solutions for a variety of problems with the functions it provides. In `more-itertools` we collect additional building blocks, recipes, and routines for working with Python iterables.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
